### ISSUE TITLE
Improve performance of Do Not Sell link detection

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#223] opened 2021-08-29 22:35 UTC
There are a few instance in the validation set that go wrong on identifying Do Not Sell links. @OliverWang13, can you fix those (if you can, please chime in here @stanleymarkman and/or @kalicki1 supporting @OliverWang13).

- https://www.gap.com/: DNS is in a `<button>` but somehow not found. @OliverWang13: The code can only find it as a `<script>`, `<body>`, or `<html>`. @SebastianZimmeck: Any idea why button detection does not work?
- https://www.rakuten.com/: @OliverWang13: Not sure why this doesn't work. @SebastianZimmeck: Was the page fully loaded when you analyzed it? Is it maybe dynamically loaded and only in the DOM but not in the page source code itself (assuming that is what you are relying on; when you right-click and `inspect` with the developer tools, do you see what you expect? Or try checking the source code of the site.)?
- https://www.adobe.com/: @OliverWang13: Sometimes works sometimes doesn't. @SebastianZimmeck: Any thoughts on why? Can you look into it?
- https://www.theguardian.com/us: @OliverWang13: Has a pop up when you enter the site, with a link to click there, which we do not detect. Then, past the popup, there is a link saying "California resident - Do Not Sell". Current RegExp does not identify the link. @SebastianZimmeck: Can we modify the regex to capture?
- https://www.businessinsider.com/: @OliverWang13: Not sure why this doesn't work @SebastianZimmeck: Any hints? 
- https://www.condenast.com/: @OliverWang13 Seems to return a false positive? Not sure why. Perhaps the link is only shown in California but still exists in the site. @SebastianZimmeck: Yes, I can confirm. There is a link when accessed with a California IP address. It is probably suppressed from being displayed to non-California IP addresses but still in the code of the page. Those instances we should actually count, i.e., they are true positives. This brings up the larger point that I should probably load all pages with a California IP once you have finalized tuning to confirm that I get the same results.
- https://www.theatlantic.com/: @OliverWang13: Not sure why this doesn't work @SebastianZimmeck: Any hints?
- https://www.newyorker.com/, https://nypost.com/: @SebastianZimmeck: Can confirm that this works in California.

**Comment by SebastianZimmeck** [comment] 2021-08-30 20:51
@OliverWang13 will look a bit more into this.

**Comment by SebastianZimmeck** [comment] 2021-09-09 18:34
@OliverWang13 will provide an update (and ideally concrete pointers) which sites are failing, what has be tried, what could be worth trying, etc.

**Comment by OliverWang13** [comment] 2021-09-09 22:48
I have tested our code on the new sites I added to the validation set. Below are notes about certain sites. An issue I think we may be having is the site triggering the window.onload function before the page is actually fully loaded, causing us to miss searching through some tags.
Here is the link to the validation set: https://docs.google.com/spreadsheets/d/19Wi2PaPsEOfiSdeaOEdSNg5QCzJbRmc7f5rHhXYzO6E/edit?usp=sharing

https://www.gap.com/: when searching for `<a>` or `<button>` or `<footer>`, it does not appear. When inspected, it appears as a button tag. When searching for all tags (`<*>`), it is found.

https://www.rakuten.com/: Is not found even when searching for `<*>`. The regex should capture "Don't sell my info", as confirmed on regex101.com.

https://www.businessinsider.com/: Is not found even when searching for `<*>`. The regex should capture "CA Do Not Sell My Info", as confirmed on regex101.com. This page is made for lengthy scrolling, so maybe the footer does not actually "exist" on the page until a user scrolls to it.

https://www.theatlantic.com/: Very similarly to business insider, the site scrolls for a long time, which may result in the same issue.

https://slate.com/: @SebastianZimmeck could you check this site from California? The link finder finds a link, but I am unable to.

@kalicki1 If you wouldn't mind quickly looking at the sites above and seeing if there is anything obvious I may have missed, I would appreciate it. 

Overall, 78/82 sites working seems pretty functional, and I am unsure if the link finder can improve to get 82/82. I would be ok with leaving it as is, assuming that Kuba is unable to find something I may have missed.

**Comment by SebastianZimmeck** [comment] 2021-09-09 23:39
Thanks, @OliverWang13! How could I run your Do Not Sell link identification code? It is not yet in our extension or is it?

**Comment by OliverWang13** [comment] 2021-09-09 23:57
@SebastianZimmeck I was more thinking that you could see if you find a Do Not Sell link manually, to confirm that it has one (as it may be a link that can only be seen from California). The identification code finds the link, but I can not confirm that the link exists. However, if you would like the code it is currently in main (in contentScripts.js, more specifically), and it prints the message "Found it" to console if it finds the link.

**Comment by SebastianZimmeck** [comment] 2021-09-10 00:50
- https://www.gap.com/: There are two things I can think of. 
   <img width="296" alt="Screen Shot 2021-09-09 at 5 33 26 PM" src="https://user-images.githubusercontent.com/11034003/132779973-1c740bcf-e0ce-4ca1-a7d4-94f36b937eff.png">
   1. Does your regex also account for the additional class they assign? The button tag is not immediately closed. Maybe, that is not captured by your regex?
   2. Maybe it is a timing issue. It seems that the Do Not Sell link language is in a script and there is also some JSON parsing happening first. Maybe, when you check the site, the language is not yet loaded? Delay a bit with `setTimeout` or something similar?
- https://www.rakuten.com/: Same two suggestions as for gap.com.
   <img width="511" alt="Screen Shot 2021-09-09 at 5 44 00 PM" src="https://user-images.githubusercontent.com/11034003/132780612-5f817b04-5220-4e3f-9ff1-4a8a82846aa3.png">
- https://www.theatlantic.com/: Same two suggestions as for gap.com
- https://slate.com/: There is indeed a link. It is in the following banner. So, this is resolved!
   <img width="1322" alt="Screen Shot 2021-09-09 at 5 23 19 PM" src="https://user-images.githubusercontent.com/11034003/132779302-a28968a5-966f-43a8-a0dc-ed01cc79da70.png">

**Comment by OliverWang13** [comment] 2021-09-15 00:10
The Regex I am using should only be compared with the `innerHTML` in the tag. I am getting the tags to look at using `getElementsByTagName()`, which does not seem to have trouble on other sites when an additional class is involved. I tried using `setTimeout`, which worked on gap.com but only when I took the few seconds to quickly scroll down and load the link, which I would not say is a suitable workaround. Other than that, `setTimeout` did not seem to be effective.

**Comment by SebastianZimmeck** [comment] 2021-09-15 03:18
@OliverWang13, can you tell me the steps that I need to do to run your Do Not Sell link identification? (Not sure how the build process actually works for a particular branch, `issue-223` in this case, assuming that is what you do.)

It would be good if we can find out why the identification does not work for the four open sites.

**Comment by OliverWang13** [comment] 2021-09-15 15:35
On my computer, I run `git checkout issue-223` and then I `npm run start` from the optmeowt folder and refresh the extension. From the chrome or firefox extension page, you may then have to navigate to the chrome or firefox folder, respectively. If this is not working for whatever reason, all added code is in the contentScripts.js folder and could likely by manually added without much difficulty.

**Comment by SebastianZimmeck** [comment] 2021-09-15 16:01
Thanks, @OliverWang13!

**Comment by SebastianZimmeck** [comment] 2021-09-15 20:14
rakuten.com can be fixed by changing the regex. They are using a `’` instead of a `'`. The detection worked for me with:

`var phrasing = /Do.Not.Sell.My|Don't.Sell.My|Don’t.Sell.My/gmi`

Maybe, you can make it a bit more succinct, @OliverWang13, as only the apostrophe is different.

gap.com, businessinsider.com, and theatlantic.com work for me when I scroll down to the footer (and for businessinsider.com I even had to "inspect" the link first with my browser before it would be found). For those sites, we have a fundamental challenge: the code for displaying the Do Not Sell link is already in the browser. It is delivered by a response request, which can be observed in the Network section of the browser developer tools. If I just normally load, say, businessinsider.com, there is already JavaScript code available even if I do not scroll to the bottom of the page:

<img width="1135" alt="Screen Shot 2021-09-15 at 1 00 26 PM" src="https://user-images.githubusercontent.com/11034003/133501291-56143433-559d-4dde-ba32-97db597043b8.png">

But that code is not yet rendered in the [DOM](https://en.wikipedia.org/wiki/Document_Object_Model) of the page. In other words, there are no tags and no other HTML yet. The Do Not Sell link is not part of the original source code of the page. It is dynamically created from JavaScript code when the user scrolls down the page (and in the case of businessinsider.com even an interaction with the link seems to be required). 

There are two possibilities to address this situation: 
1. programmatically scroll down the page, let the page create the DOM, then check for the link
2. do not (solely) rely on the rendered page, tags, etc, but instead look in the intercepted HTTP response (i.e., the JavaScript code) for code that may create a Do Not Sell link

Possibility 1 is probably hard to do within an extension. Probably, we would need Selenium or some other automation to accomplish that. But who knows, maybe there is a browser API that allows scrolling down. So, I would check that.

Possibility 2 is likely doable in an extension but would fundamentally change the nature how we search for Do Not Sell links (and we may even need two ways for detecting those links: on the already rendered page as currently because some sites may just straight put their link in a site's HTML and in a new way by intercepting the HTTP response). This is worth exploring in more detail because essentially @kalicki1 and @stanleymarkman are already using interception techniques, for example, to identify cookie headers with US Privacy String values.

**Comment by OliverWang13** [comment] 2021-09-16 14:26
Yes, the regex can be simplified to:
`var phrasing = /Do.Not.Sell.My|Don.t.Sell.My/gmi`
As for the two possibilities, the first possibility seems like it could work in a batch analysis sense, but would be cumbersome for the casual user who is using analysis mode. With that in mind, I am leaning towards the second possibility.

**Comment by SebastianZimmeck** [comment] 2021-09-16 18:35
> Yes, the regex can be simplified to:
> var phrasing = /Do.Not.Sell.My|Don.t.Sell.My/gmi

Great!

As we discussed today, @OliverWang13 will explore possibility 2 with the help of @kalicki1 and @stanleymarkman as it is similar to combing through the network requests for the privacy flags.

Beyond possibility 2, @stanleymarkman also brought up the idea of loading the site in a scaled dimension, e.g., for mobile, so that a link in a footer is actually rendered. This would be interesting technique-wise and a point to mention in our paper.

**Comment by OliverWang13** [comment] 2021-09-20 12:51
With the new regex expression, I will work my way through the link spreadsheet once again. The header code that was put in is not currently working but is mostly an example that @kalicki1 and I found. I will continue to experiment with it and see if I can get it working.

**Comment by SebastianZimmeck** [comment] 2021-09-20 17:44
> With the new regex expression, I will work my way through the link spreadsheet once again. The header code that was put in is not currently working

Maybe, take the pass when you are done with the header code? That way you would not have to do it then again. Also, if the current regex change is just the type of apostrophe, there should not be different results than before. So, the bottom line is to organize this testing economically.

**Comment by SebastianZimmeck** [comment] 2021-09-23 17:22
@OliverWang13 looked into changing the resolution to make the site appear smaller and load more content and requests, but that does not work. Now, @OliverWang13 is looking into dynamically intercepting headers. First, @OliverWang13 will check in principle whether the interception of "Do Not Sell" language works, and secondly, if so, how to process the result from that interception further (e.g., saving at the backend, displaying in the UI).

**Comment by OliverWang13** [comment] 2021-10-03 18:39
@kalicki1 and I worked on this together and were able to implement a link finder for dynamically loaded links. This new method works on 3/4 of the sites we were unable to catch, which gap.com being the exception. As of now, the old DNS link finder is not running, but this is likely due to messy code from when I brought the branch closer to main.

**Comment by SebastianZimmeck** [comment] 2021-10-04 01:25
Nice, @OliverWang13 (and @kalicki1)!

> This new method works on 3/4 of the sites we were unable to catch, which gap.com being the exception. 

- Do you have thoughts on the reason(s) and how performance can be improved?
- Also, does that meant you tested the new method on just four sites? If so, we would need a bit more. Could we test on the complete validation set? 
- Would the combination of old and new method possibly be more performant than each on its own?

**Comment by kalicki1** [comment] 2021-10-05 03:35
@SebastianZimmeck I can speak to your first question:

(1) We think that the Gap site still won't show in either detection method simply because, we believe, the DNS link isn't sent until the bottom of the page is requested. This means, unless we find some API to help us (my thinking is this is unlikely), we would still have to automate some sort of scrolling to get it to show.  

About your last two points: (2) Yes, we should test on the entire validation set after we get it fully running and (3) we have not yet but should test whether the combination of old and new is better than each on its own.

**Comment by SebastianZimmeck** [comment] 2021-10-05 19:50
Thanks, @kalicki1!

> We think that the Gap site still won't show in either detection method simply because, we believe, the DNS link isn't sent until the bottom of the page is requested.

I checked https://www.gap.com/ again. I accessed the site without any scrolling or other navigation. Then, I searched in the network requests for "do not sell" and saw a reference there in a response the site sent.

<img width="1387" alt="Screen Shot 2021-10-05 at 12 40 33 PM" src="https://user-images.githubusercontent.com/11034003/136092142-38852814-78c7-47b2-9453-1c4b35d53e81.png">

Here is the excerpt of the `window.__SITEWIDE_APP_STATE__ = JSON.parse` response code with "Do Not Sell" in it. 

<img width="1027" alt="Screen Shot 2021-10-05 at 12 39 18 PM" src="https://user-images.githubusercontent.com/11034003/136092183-d9d98e9c-744c-43ed-8433-ef16f2d3c00b.png">

We should be able to see that, right? If not, are we checking too early before the response is received in the browser?

Can you and @OliverWang13 look into that?

> (2) Yes, we should test on the entire validation set after we get it fully running

Excellent!

> (3) we have not yet but should test whether the combination of old and new is better than each on its own.

As the major shortcoming of the previous method was that we could not see the response data, I do not think we would see any improvement in a combination of the two methods unless we can get the response data functionality working.

**Comment by kalicki1** [comment] 2021-10-14 16:47
I managed to get the Gap site logging this week without requiring user input on the site 🎉

The `webRequestFiltering` API we use to pull the data was not implemented fully correctly in order to catch everything we needed to. I refactored this code so that the filter itself did not close before everything was analyzed, and this managed to solve the issue. I now have a `filter.onstop` event that listens for the page to stop loading before processing any of the responses.

**Comment by notowen333** [comment] 2021-10-14 18:29
@kalicki1 If you want, feel free to shoot me a message on teams and we can schedule a Zoom or meet at the lab. 

@SebastianZimmeck is correct that imposing a size limit had the best results. 

Basically, you just close the filter `filter.disconnect()` if the stream exceeds an arbitrary length (we choose 200k bytes).

## Implementation

```
const filter = browser.webRequest.filterResponseData(details.requestId)

  var responseByteLength = 0,
   abort = false,
   httpResponseStrArr = []

  filter.ondata = (event) => {
    if (!abort) {
      filter.write(event.data)
      responseByteLength += event.data.byteLength
      if ( responseByteLength > MAX_BYTE_LEN ) {
        filter.disconnect()
        abort = true
      }
      else {
        const str = decoder.decode(event.data, { stream: true })
        httpResponseStrArr.push(str)
      }
    }
  }

  filter.onerror = (event) => (request.error = filter.error)

  // when the filter stops, close filter, add data from httpResponseStrArr to
  // our Request created earlier. Sends to resolveBuffer (below)
  filter.onstop = async (event) => {
    if (!abort) {
      filter.close()
      request.responseData = httpResponseStrArr.toString()
      resolveBuffer(request.id, data)
      }
  }
```

**Comment by OliverWang13** [comment] 2021-10-29 20:21
I have removed the old `do not sell` link finder in main and will be closing this issue.

**Comment by kalicki1** [comment] 2021-11-04 16:14
I am reopening this to make a small comment about the commit I added above: 

For some reason after removing the DNS link finder, our script injection process from `contentScript.js` broke. I rearranged some of the code and got it working again. I believe this should be ready for us to test as a whole at this point in time.

**Closed by kalicki1** 2021-11-04 16:14 UTC
Labels: bug, top priority, analysis
