### ISSUE TITLE
Update DOM signal

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#259] opened 2022-03-31 19:45 UTC
The last big issue in our migration to MV3 is to make sure the GPC DOM signal is working correctly. I believe that I read that we will need a 3rd party library for this functionality, but if we can make it work without, that would be ideal. 

@OliverWang13 will take the lead on this and I will help out.

**Comment by SebastianZimmeck** [comment] 2022-04-15 02:08
Per our discussion today, @OliverWang13 will try to finalize this issue within the next two weeks, at which point we should be done with the whole [mv3 migration](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/175).

**Comment by OliverWang13** [comment] 2022-04-18 01:53
A common issue I have run into while testing a few things is the following error:
![Screen Shot 2022-04-17 at 9 40 19 PM](https://user-images.githubusercontent.com/82842273/163741742-b7a39817-2623-4604-9a4f-89a1d960a728.png)
It seems like we are able to inject a `<div>` tag but not a `<script>` without getting this error.
@kalicki1 and I are looking into this.

**Comment by SebastianZimmeck** [comment] 2022-04-18 01:59
Sounds good! Maybe, @chunyuema and @ekuller know.

**Comment by SebastianZimmeck** [comment] 2022-04-21 19:15
@OliverWang13 is going to schedule a meeting with @chunyuema and @ekuller to talk about this. If we cannot figure it out, we can also reach out to DuckDuckGo.

**Comment by kalicki1** [comment] 2022-04-28 18:09
I've been trying to narrow this down but it is a tough issue to crack.

What we know is that whenever we try to attach a GPC DOM signal, **we are doing it through content scripts**, regardless of whether we are using a script declared in the manifest or with the `scripting.executeScript` API (the script becomes a content script).

I am trying to figure out the technical details regarding how a content script can interact with its host page. As far as I know, a content script's scope is the host page, however it seems that it is still fully isolated and we can't modify the host page in the way we want. We can attach any new DOM element, e.g. change all visible pictures to pictures of cats, etc., as long as it is not a <script> element. We use script elements to add the `navigator.globalPrivacyControl` property in MV2 (this is the issue @OliverWang13 outlined above). 

I'm not sure about the way forward. We need to figure out a way to attach GPC without needing a <script> element. I don't believe we can give it permission to do so (i.e. inline-scripting) if we want to push to the Chrome store. I think this issue will entail figuring out how to give content scripts permission to access the host page but I don't believe we will be able to as it would let us circumvent the inline-scripting restriction.

**Comment by kalicki1** [comment] 2022-04-28 18:19
@SebastianZimmeck, we actually have met to discuss this. It sounds like they haven't taken a deep look at the issue either. Our best guess from our talk is that the change in the extension permissions intentionally prevents the kind of access we need.

**Comment by SebastianZimmeck** [comment] 2022-04-28 18:20
Ah, OK! Great! Maybe, you can explain more in our call because I would like to understand what we do differently here.

**Comment by kalicki1** [comment] 2022-04-28 18:43
Related Reddit link: 
https://www.reddit.com/r/chrome_extensions/comments/tdzqon/how_to_inject_script_tag_into_webpage_with/

**Comment by npdoty** [comment] 2022-04-28 20:17
per https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#inline_javascript can you add a content script that is a local file in the extension, rather than inline script contents?

**Comment by SebastianZimmeck** [comment] 2022-04-28 21:00
@chunyuema confirmed that, indeed, the DOM signal is not resolved in the GPC Privacy Choice extension (which is OK for the purposes there).

**Comment by SebastianZimmeck** [comment] 2022-05-05 18:39
@kalicki1 will try to work on this over the next couple of days.

**Comment by kalicki1** [comment] 2022-06-06 15:52
Overall, this seems to be resolved as long as we are okay with the DOM property potentially being set not as early as it used to be. I believe this is related to how service workers function, though I am not 100% sure. 

In the most recent version of branch issue-175, I have created a content script to inject the GPC DOM property if it is appropriate to do so. This is accomplished via a query message sent from the content script to the service worker who verifies the target domain against its domainlist. Currently, this works correctly as I can verify the DOM property is attached when it is appropriate through a target site's console. However, it does seem that there may be a timing issue which may impact client-side detection. I observed that on occasion the GPC reference server may show 'thumbs down' when the DOM property is attached. The 'thumbs up' and 'thumbs down' will flip back and forth randomly when I refresh. 

@SebastianZimmeck, if I remember correctly you may have mentioned that it is okay if we have this 'late' behavior; is this right? If so, we can go ahead and close this issue out. We can also resolve this after we merge our MV3 code into the main branch if we feel it is necessary.

**Comment by kalicki1** [comment] 2022-06-06 17:24
@OliverWang13, do you mind taking a look at DDG's privacy essentials extension to see if they have resolved the GPC DOM timing issue? This would involve taking a look at their codebase to see if they do the message passing we do, if they keep the SW alive persistently, etc.

**Comment by OliverWang13** [comment] 2022-06-11 16:37
DDG's gpc implementation is found in the `inject.js` file around line 3130 once you have built the extension. `inject.js` is listed as a content script that runs at `document_start`. Their current live versions are all MV2 however, so it is not clear whether they have been able to get MV3 working or not.

**Comment by SebastianZimmeck** [comment] 2022-06-12 15:51
Help! :) @npdoty, @dharb, @pes10k, if you guys have any thoughts, we would appreciate it very much. As we are switching to MV3, we have a [slight problem](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/259#issuecomment-1147605437) with the timing of injecting the GPC signal via the DOM. We looked at DDG Privacy Essentials, but, @dharb, it looks like you are in the middle of the move as well ... .

**Comment by npdoty** [comment] 2022-06-13 18:25
+1 that it looks like you'll want a content script, so that you can specify `document_start`. Is the race condition happening because you're doing an asynchronous call to the service worker to look up the domain, and so in the meantime the page has loaded and its own scripts may have run? You might want to make this synchronous, but also, you really want this to be an immediate process, rather than requiring a dynamic look-up, as it would really annoy the user if every page load is slowed down by trying to determine which GPC value should be there.

**Comment by npdoty** [comment] 2022-06-14 16:08
`chrome.storage.local` seems worth trying, since it's designed partly for shared storage for extensions. Those APIs are still asynchronous, but maybe it's still faster than querying the service worker?

You could also embed all the data in the registered content script, so that it was a direct look-up in a local object. But that might be challenging to make more dynamic, I'm not sure.

**Comment by kalicki1** [comment] 2022-06-14 18:06
I threw together a simple, though incomplete, implementation with `chrome.storage.local` for testing the DOM signal. It seems it is faster to query the service worker than IndexedDB and more consistently loads the right preference on the reference GPC website, but still encounters the race condition. I don't think it's worthwhile spending more time on this API since it's asynchronous. 

(Just a heads up, branch issue-259 broke the GPC header for some reason, I didn't debug it.)

@SebastianZimmeck, I'm wondering if this means we should go with an MV2 version for our study (tagging #286). @npdoty's suggestion sounds like it would work but implementing it might take longer than we want if we hope to get started this week.

**Comment by SebastianZimmeck** [comment] 2022-06-14 18:10
Thanks, @kalicki1! I would say, take a look and try to gauge how long @npdoty's suggestion may take. If we are talking about two weeks, it is not a problem. However, if it would take month or longer, the MV2 version is probably better to pursue for the time being.

**Comment by SebastianZimmeck** [comment] 2022-06-20 16:40
As we discussed, this is the major blocker at the moment. Thus, we will make a concerted effort over the next days lead by @kalicki1 to try getting a handle on this issue.

**Comment by kalicki1** [comment] 2022-06-20 17:00
As discussed today, we will try to figure out someway of "preloading" a user's domainlist on the content script responsible for setting the GPC JS property. As there are currently no synchronous storage APIs that share data between the service worker and the content scripts, having the data loaded into a local object on the content script would make domainlist lookup immediate, or effectively "synchronous." 

Currently I'm thinking we should try to figure out if the [`chrome.scripting.registerContentScripts` API](https://developer.chrome.com/docs/extensions/reference/scripting/#method-registerContentScripts) is what we want to use. For example, can we register non-static content scripts (scripts that aren't saved to their own file, such as a specific function) similar to the [executeScript API](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript). If so, we would then be able to modify this function with the updated domainlist when a user changes their opt-out preference for a domain and immediately reregister the content script for the next time a user navigates there. 

We may have to look into whether there are other APIs that have this functionality or if there are alternative ways of achieving this.

**Comment by SebastianZimmeck** [comment] 2022-06-23 19:21
@OliverWang13, is this DOM issue a problem just for new sites and/or for sites on the domainlist?

It would be good if you can lay out the program flow and where we can encounter the problem.

And also document a bit what you have looked into.

**Comment by OliverWang13** [comment] 2022-06-23 20:19
How we are currently sending the DOM signal:
### Step 1: This code runs in `control.js` and is the first thing the extension does.
![Screen Shot 2022-06-23 at 4 00 45 PM](https://user-images.githubusercontent.com/82842273/175386968-435cb7e5-879a-4c34-b512-19de1909f086.png)

### Step 2: `content-scripts/registration/gpc-dom.js` runs on every page and sends a message.
![Screen Shot 2022-06-23 at 4 03 56 PM](https://user-images.githubusercontent.com/82842273/175387427-f76f7edb-cde3-42c8-9f54-f1045b859fc7.png)

### Step 3: `protection.js` receives the message.
![Screen Shot 2022-06-23 at 4 06 15 PM](https://user-images.githubusercontent.com/82842273/175387892-ff2fa277-d762-4b15-a224-e169dad30ca8.png)

### Step 4: We are then pointed to the function `sendPrivacySignal` which returns whether a site should get a signal or not.
![Screen Shot 2022-06-23 at 4 07 12 PM](https://user-images.githubusercontent.com/82842273/175388213-abc64f17-fea7-4321-a2be-1bccf3821411.png)

`extensionEnabled` is whether the extension is turned on or not.
`extensionDomainlisted` is whether the extension is in domain list mode (sending signals only to sites according to the domain list as opposed to sending signals to all sites)
`domainDomainlisted` is whether the domain has gpc enabled or not (`domainDomainlisted = null` if gpc is enabled)

### Step 5: The message receiving function receives `sendSignal` and sends the boolean value back to `content-scripts/registration/gpc-dom.js`
![Screen Shot 2022-06-23 at 4 06 15 PM](https://user-images.githubusercontent.com/82842273/175387892-ff2fa277-d762-4b15-a224-e169dad30ca8.png)

### Step 6: According to the boolean response, injectStaticScript is run.
![Screen Shot 2022-06-23 at 4 15 24 PM](https://user-images.githubusercontent.com/82842273/175391231-670386d1-5cbd-4195-a803-46f50b16e5d5.png)
The link that was cut off https://stackoverflow.com/questions/9515704/use-a-content-script-to-access-the-page-context-variables-and-functions

### `content-scripts/injection/gpc-dom.js`
![Screen Shot 2022-06-23 at 4 18 31 PM](https://user-images.githubusercontent.com/82842273/175392094-ae015794-28e6-42cf-a3fa-6f40b8dc8329.png)

**Comment by OliverWang13** [comment] 2022-06-23 20:27
I have read through https://github.com/Tampermonkey/tampermonkey/issues/644 and some of the links posted there
- Discussion: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/hQeJzPbG-js
It seems as though they have not been able to figure anything out yet, and they have a large user base that is upset about it.

After searching for some open source ad blockers I'm looking through https://github.com/uBlockOrigin/uBlock-issues/issues/338 to see if they have figured anything out.

**Comment by OliverWang13** [comment] 2022-06-23 20:37
This is the best that Adguard has (does not seem helpful) https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1991

**Comment by SebastianZimmeck** [comment] 2022-06-24 00:01
> How we are currently sending the DOM signal:

Thanks, @OliverWang13! 

Here is an approach:

### 1. Diagnose

Can you first diagnose the problem? How often is the GPC signal injected too late? I believe @kalicki1 mentioned about 10% of the time. Can you confirm this? Can you reproduce the problem? Is there any pattern to it (e.g., for sites on the domainlist only, for new sites only, ...)? If necessary, add additional console logs to see what happens at what point in time (possibly with a [UNIX timestamp](https://attacomsian.com/blog/unix-timestamp-javacript)). If we have the problem rarely, say, 1% of the time, we can let it go. If it is 10% or more, we should continue working.

### 2. Create and analyze minimum working example of our current approach
Assuming we have a problem, is this a fundamental problem with our current approach or do we have a problem because our concrete code takes too much time because of all the back-and-forth message passing etc. Using the same technique we are currently using can you create a minimum working example of our technique? This can be outside of our extension. Just a quick script. Can we simply attach a GPC value to site (no conditions, just straight attach the signal to every site, as barebones as this can be done)? Do we still have the problem? If yes, we need to think of a new approach. If no, the solution may be to simplify the logic of our code to attach the signal quicker. Can we simplify our logic such that the race condition does not occur? (see also below 4.)

### 3. Research out different ways of injecting and possibly ask on Stackoverflow
Especially, if we need a new approach, we should research out our options. I came across a few posts on Stackoverflow, e.g., [here](https://stackoverflow.com/a/9517879) or [here](https://stackoverflow.com/questions/70474845/inject-javascript-from-content-script-with-a-chrome-extension-v3). Are helpful for us? Play around with them, @OliverWang13.  We can also post on Stackoverflow ourselves.

### 4. Restructure our logic to fail on the side of caution
Assuming we can't get hold of the problem, I would rather err on the side of sending too many GPC signals as opposed to too few. Our users opt out more than they do not opt out. There is also less harm of opting you out when you did not want to as opposed to the other way around. Can we change the logic of our code such that the default value for any site visited is sending a GPC signal? Then in a second step of the new logic, this default value would be modified by the domain list or if the user disabled GPC. If that modification comes too late, it is tolerable.

### 5. Briefly stop loading a site
This may be also an option, but one that we should be very careful with, and I am not a big fan of it. Can the loading of a page be slightly delayed, e.g., along the lines of `setTimeout()`. This should be unnoticeable by the user, and we should avoid any degradation of the user experience.

**Comment by OliverWang13** [comment] 2022-06-24 21:06
> Can you first diagnose the problem? How often is the GPC signal injected too late?

I can check this out and rerun it a few times to get an idea of how often this problem occurs. As it could differ between devices and networks, perhaps @sophieeng and @SebastianZimmeck could do it as well. I will include some brief instructions: 

- If you travel to the main branch (`git checkout main`)
- compile the extension (`npm run start`) or (`npm run build`)
- load the extension on chrome, navigating to the proper optmeowt folder (dev/chrome if you did `npm run start`, dist/chrome if you did `npm run build`
- travel to https://global-privacy-control.glitch.me/
- take note if the DOM signal has been set or not (indicated by a blue thumbs up in the client-side detection section)
- reload a few times, keeping track of how often you have reloaded and how often it has displayed a thumbs down
- create a proportion of (times failed)/(times reloaded)

This will give us an idea of how often it happens on this site, but I can do further testing on other sites.

**Comment by OliverWang13** [comment] 2022-06-24 21:07
I just ran this methodology and reloaded the site 105 times and only had it fail once, which is a lot less than I had previously expected. Let me know what you guys find.

**Comment by SebastianZimmeck** [comment] 2022-06-25 14:16
Great news! If the failure rate is just 1%, I would find that tolerable. We can include a reference in our readme in the Known Quirks section and move on.

@sophieeng, can you test as well according to the [methodology](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/259#issuecomment-1165939982) given by @OliverWang13 ? What do you find?

@OliverWang13, is there a way you can also test with other sites beyond the Glitch sample implementation? For example, if you take the handful of sites that we already retested and know to react to implement DOM-based GPC, what is the result there?

**Comment by OliverWang13** [comment] 2022-06-26 16:48
I am trying to figure out how we can test different sites, but nothing has immediately popped out to me that works. Below are some ideas I have tried.
- Loading a new site and checking the value of `navigator.globalPrivacyControl`. This doesn't work because no matter when the DOM signal is added, as long as it is added eventually, `navigator.globalPrivacyControl` will return true after that point. It seems inconsistent to try and check the value to see how quickly the signal is set without a frame of reference for when the site needs the DOM signal.
- Loading a new site and disabling the header sending, so only the DOM signal is sent, then checking the USPAPI to see if we have been correctly opted out (only on sites we know respect GPC). The problem here is that I am not sure if sites look at the DOM signal or the headers for setting the USPAPI. I could do some further testing on a site-to-site basis to try and figure this out, so I might proceed with that.

**Comment by SebastianZimmeck** [comment] 2022-06-26 18:02
> The problem here is that I am not sure if sites look at the DOM signal or the headers for setting the USPAPI.

You could check the sites that respect GPC and use the USPAPI (and disable the header to be sure that you are not accidentally measuring those results for sites that may do both). We know the ground truth for the sites that we analyzed in our Google Sheet (column U: USP String Implementation [cookie, uspapi, both, na]). Whatever method we used there, should also work to identify new sites' usage of header vs USPAPI. 

You can check use of the USPAPI via the browser developer tools console:

`__uspapi('getUSPData', 1, (data) => console.log(data))`

The implementation guide is [here](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/USP%20API.md).

Also, not sure if the implementation is different on our site

https://www.privacytechlab.org/optmeowt/

and can be used for testing compared to the sample implementations on Glitch. Maybe, it makes a difference given the overall implementation (not sure; @kalicki1 implemented our site).

**Comment by OliverWang13** [comment] 2022-06-26 22:20
For now, I will visit sites that we recorded as honoring gpc, run optmeowt without sending headers, and see if we are opted out with uspapi. If not, I will take another look to see if they still respect gpc and if they require headers to change the uspapi.
- cnn.com : worked
- latimes.com : worked
- nypost.com : not worked
- nationalgeographic.com : not worked
- nj.com : worked 
- mlive.com : worked
- al.com : worked 
- washingtonpost.com : worked
- weather.com : worked 
- arstechnica.com : worked 
- nba.com : worked

**Comment by OliverWang13** [comment] 2022-06-28 12:06
I am trying to start the testing of other sites to analyze the performance of the DOM signal, but it seems as though before sending the GPC dom signal we will be opted in, and afterward, we will be opted out (which makes sense). However, testing with the current methodology I am using will not prove anything. We know that the DOM signal is correctly injected eventually. But we do not have an idea of if there is a time the DOM signal needs to be set.

**Comment by SebastianZimmeck** [comment] 2022-06-28 17:31
As just discussed, getting a handle on the timing by checking via console log messages (Unix timestamp + USPAPI value) in the critical pieces of code may get us some insight.

**Comment by OliverWang13** [comment] 2022-06-28 22:47
I implemented the Unix timestamp only because on a site that implements GPC, the USPAPI value should change (and fetching it from the page may cause further time delays. I will run the code on a site 5 times then record the amount of milliseconds it took between document start and the injection of the dom signal.

- https://global-privacy-control.glitch.me/ : 104 - 1331 - 245 - 87 - 100
- cnn.com : 1868 - 2149 - 1388 - 1964 - 1851
- latimes.com : 2694 - 3898 - 2922 - 3587 - 3053
- nj.com : 3559 - 3754 - 2618 - 256 - 4145
- washingtonpost.com : 12363 - 11660 - 12381 - 11642 - 1186
- weather.com : 464 - 1308 - 1576 - 1374 - 1311
- arstechnica.com : 4730 - 1040 - 3375 - 386 - 2255
- nba.com : 5903 - 5466 - 7261 - 6315 - 5915

These times feel pretty scattered and I wonder if there is a relationship to the number of requests the site has and the amount of time it takes.

**Comment by SebastianZimmeck** [comment] 2022-06-29 23:54
OK, so we know now then that the issue is mostly on our end and less with sites' general page load speed.

**Comment by SebastianZimmeck** [comment] 2022-06-29 23:56
The question is, is it enough if the DOM signal is injected eventually (and the US Privacy string changes) or is speed relevant? This question is slightly different from what we were discussing before that the DOM signal was not attached at all, which definitely would be a big issue if it occurs frequently. Though, for speed, I am not sure what is fast and how much it matters.

**Comment by OliverWang13** [comment] 2022-06-30 01:50
I'm experimenting a little bit more to improve the timing, specifically with https://www.npmjs.com/package/webext-content-scripts
It looks somewhat promising and was just published 12 days ago, but I am having trouble getting it to work.

**Comment by SebastianZimmeck** [comment] 2022-06-30 02:20
Let's make sure we use only well-supported libraries. It is not great when a developer stops updating, things break, and we have to find a new solution (general comment; I do not know this library).

**Comment by OliverWang13** [comment] 2022-07-01 01:02
Currently I'm experimenting with registering content scripts, no luck yet but I will keep trying things. I am wondering if we can do things like we do the rules, we have one large rule that sends the GPC dom to all sites, and then register unique content scripts to counteract the major rule.

**Comment by SebastianZimmeck** [comment] 2022-07-01 01:04
> sends the GPC dom to all sites, and then register unique content scripts to counteract the major rule.

Yes, that is worthwhile trying out (after confirming that sending the GPC dom to all sites solves our page speed load problems).

**Comment by OliverWang13** [comment] 2022-07-01 17:36
I am opening a new branch issue-260 to record some changes that I made, as issue-259 is not up to date with our current code base. Tentatively, I think I found something that works, but seems like it has broken something else, so I will have to look further into it.

**Comment by OliverWang13** [comment] 2022-07-03 19:41
I know it is messy, I made a few branch mistakes but now branch issue-261 has the most up-to-date things I have been working with.

**Comment by OliverWang13** [comment] 2022-07-05 23:41
I think that this is completed now, so I will be closing it.

**Closed by OliverWang13** 2022-07-05 23:41 UTC
Labels: core functionality, top priority, mv3
