### ISSUE TITLE
OptMeowt causes my online bank to LogMeowt

### ISSUE THREAD

**Issue by ldoron** [privacy-tech-lab/gpc-optmeowt#441] opened 2023-11-28 13:50 UTC
I have a problem with logging into my bank's web site. The bank itself is https://www.watertownsavings.com/, but its online banking is hosted at https://retailonline.fiservapps.com/Login/211370176. When OptMeowt is installed, then immediately after I log in, I get a dialog box with a message from the site: "For security reasons, your session has ended. Log in again.". When I click OK, it takes me back to the login page. Before I click OK, I can see the static elements of the account web page, but the dynamic ones with any personal financial info just show a spinning wheel. I've attached a screen shot below.

The behavior is the same on Google Chrome and Microsoft Edge. The only way I can log in is if I turn off the entire extension through the *browser's* "Extensions" management page. If leave OptMeowt running, but use its "Disable" option (pause button icon), the problem still occurs. (Likewise if it's enabled, but I turn off "Do not sell" for the site and all third-party domains.)

If I turn off the extension, log in successfully, and then turn it on again, the next time I load a page from that site, I get the same security message and get logged out.

The behavior I'd expect is that I should be able to disable OptMeowt for just the banking domain and use the banking web site without issues.

![1CCeJRwWSTDp9BVS](https://github.com/privacy-tech-lab/gpc-optmeowt/assets/19734903/6651218c-2527-4265-94e9-ffb60daaa520)

**Comment by Jocelyn0830** [comment] 2023-12-10 17:36
I have been working on replicating this issue on my end. I was not able to replicate the exact same situation. The problem I found is that when I logged into some account with OptMeowt enabled, toggled off the switch "Do Not Sell Disabled" and refresh, I was logged out from my account automatically each time. The "Disable" button does not have the same effect. This issue may be related to the problem with bank site.

**Comment by SebastianZimmeck** [comment] 2023-12-10 18:45
>  I was logged out from my account automatically each time

How could we fix that?

**Comment by OliverWang13** [comment] 2023-12-15 19:27
> How could we fix that?

see #443

**Comment by OliverWang13** [comment] 2023-12-18 20:38
@ldoron, sorry for the lack of progress made here, there isn't a lot we can do without being able to replicate your issue (we have never encountered a site that reacts in the way Watertown Savings does).

Just to confirm, this is an issue caused by the reaction between OptMeowt and Watertown Savings, not a reaction between GPC and Watertown Savings (e.g., turning on GPC [in the firefox browser](https://blog.mozilla.org/netpolicy/2021/10/28/implementing-global-privacy-control/) or using another privacy extension/browser that implements GPC).

**Comment by SebastianZimmeck** [comment] 2023-12-26 20:26
@OliverWang13 will inquire as discussed.

**Comment by OliverWang13** [comment] 2024-01-17 15:21
I will close this and reopen it if needed/ if Watertown Savings Bank responds.

**Comment by SebastianZimmeck** [comment] 2024-01-17 15:23
Sounds good! And if you could add a sentence in the known issues readme section and link to this issue.

**Closed by SebastianZimmeck** 2024-01-17 15:23 UTC
Labels: bug
