### ISSUE TITLE
Fix analysis mode UI

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#344] opened 2022-08-03 20:44 UTC
It seems to me there is something wrong with the green checkmarks and/or the Privacy String displayed in the popup.

Here is an analysis where the site respects GPC: the checkmark in the fourth line is green and the third position character in that line is Y.

<img width="1147" alt="Screen Shot 2022-08-03 at 4 34 21 PM" src="https://user-images.githubusercontent.com/11034003/182707347-81cad188-0424-4dfe-8a4c-1da7a22a6435.png">

Here is an analysis where the site does not respect GPC: the checkmark in the fourth line is red and the third position character in that line is N.

<img width="1091" alt="Screen Shot 2022-08-03 at 4 35 51 PM" src="https://user-images.githubusercontent.com/11034003/182707712-d1ba7bc8-34e3-4c80-89af-33dfcc38f69f.png">

Now here is the problem. Here is an analysis where the site does respect GPC or not? The checkmark in the fourth line is green and the third position character in that line is N.

<img width="707" alt="Screen Shot 2022-08-03 at 4 22 12 PM" src="https://user-images.githubusercontent.com/11034003/182707859-5e91cf40-3447-46f6-aad8-bd2148457c69.png">

I believe the issue is with the string and the checkmark seems to right. Either way, this combination of N and green does not go together.

**Comment by Jocelyn0830** [comment] 2022-08-03 22:22
I tried to replicate this problem on my end. For me, I have a combination of N and red, but the ground truth is 1YYY. 
<img width="1339" alt="Screen Shot 2022-08-03 at 18 20 52" src="https://user-images.githubusercontent.com/102534933/182722505-f59ee1e6-8259-4e84-b14b-6f032869f9c1.png">

**Comment by Jocelyn0830** [comment] 2022-08-04 01:51
> Now here is the problem. Here is an analysis where the site does respect GPC or not? The checkmark in the fourth line is green and the third position character in that line is N.
> 
> <img alt="Screen Shot 2022-08-03 at 4 22 12 PM" width="707" src="https://user-images.githubusercontent.com/11034003/182707859-5e91cf40-3447-46f6-aad8-bd2148457c69.png">
> 
> I believe the issue is with the string and the checkmark seems to right. Either way, this combination of N and green does not go together.

I tested the analysis mode on https://www.freep.com/ for a couple of times. I was not able to reproduce the result @SebastianZimmeck got. In addition to my last comment, I also got something like
<img width="1333" alt="Screen Shot 2022-08-03 at 21 44 57" src="https://user-images.githubusercontent.com/102534933/182745529-7647ebb3-f431-4473-a38a-3f04e4d69f58.png">

I read through the code and I didn't find any logical errors, but I may need to look more into that as well. My guess now is that [the site](https://www.freep.com/) messes up the privacy string. I am also wondering if there are any other sites that show the same problem.

**Comment by SebastianZimmeck** [comment] 2022-08-04 04:02
OK, so here is what I do in detail:

1. Clear all browser data and history

<img width="595" alt="Screen Shot 2022-08-03 at 11 52 37 PM" src="https://user-images.githubusercontent.com/11034003/182759415-96db98eb-e966-4cbd-9b61-067c956827b9.png">

<img width="580" alt="Screen Shot 2022-08-03 at 11 53 21 PM" src="https://user-images.githubusercontent.com/11034003/182759495-b9d559a6-e6e2-4194-bc4a-9449cc7f87df.png">

2. Enable OptMeowt (no other add-ons active)
3. Visit freep.com
4. Bring up the browser developer tools

<img width="1102" alt="Screen Shot 2022-08-03 at 11 54 54 PM" src="https://user-images.githubusercontent.com/11034003/182759674-f21e912d-aedc-4446-bf0f-d260f23fb61d.png">

5. Do an analysis in analysis mode. I stop it after about 20 seconds when there is 3 or 4 seconds nothing new loaded. So far so good. I get 1YNY.
6. Now, I do another analysis just as in the previous step, and I get:

<img width="480" alt="Screen Shot 2022-08-03 at 11 58 29 PM" src="https://user-images.githubusercontent.com/11034003/182760022-7b1dfd10-9f99-40ad-8365-501c8b055947.png">

7. Running `__uspapi('getUSPData', 1, (data) => console.log(data))` in the console shows `1YYY`. So, yes, they are a little bit slow, possibly because there is so much loaded on the site, but ultimately, the site seems to do the right thing.

Maybe, we still have the old result string stored somewhere.

**Comment by SebastianZimmeck** [comment] 2022-08-04 04:08
When I disable and re-enable OptMeowt and then run a third analysis, the analysis string is correct 1YYY with green checkmark.

<img width="360" alt="Screen Shot 2022-08-04 at 12 07 46 AM" src="https://user-images.githubusercontent.com/11034003/182760945-1329fa0b-9d3d-4e98-9532-a507f5e03c52.png">

**Comment by SebastianZimmeck** [comment] 2022-08-06 23:28
Essentially, this is a problem of updating the analysis results in the popup when an analysis is run multiple times. It is OK to overwrite the previous results. However it appears that currently the checkmark is updated while the string is not. The behavior should be consistent and the string should be updated as well. 

Also, what is the situation in the analysis list? Do we also have the same issue as in the popup? If yes, it should be fixed there as well. And there should be consistency between what is displayed in the popup and the analysis list.

This is a fairly minor issue and not worth it to spend a lot of time on. If it is too tricky to resolve, add an entry to the Wiki as a known issue.

**Comment by Jocelyn0830** [comment] 2022-09-04 15:19
> Also, what is the situation in the analysis list? Do we also have the same issue as in the popup? If yes, it should be fixed there as well. And there should be consistency between what is displayed in the popup and the analysis list.

The situation in the analysis list as well as the exported csv data is the same as in the popup. 

The way I resolved this issue is to overwrite the previous result, which seems to work well.

**Comment by Jocelyn0830** [comment] 2022-09-04 18:28
This should be fixed now.

**Closed by Jocelyn0830** 2022-09-04 18:28 UTC
Labels: bug, analysis, ui
