### ISSUE TITLE
Popup Icon Not Changing Color

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#306] opened 2022-07-07 15:19 UTC
An issue discovered from #289. 

The icon is supposed to change when different things are detected (ie GPC signal is sent, analysis mode is on/off, or .well-known is present). In MV3, Chrome changed the API chrome.browserAction to chrome.action and made the API return a promise. I believe this is why the icon is not changing, but it is possible it comes from some other disconnect because of a change between MV2 and MV3.

**Comment by OliverWang13** [comment] 2022-07-07 16:38
I checked this out a little. From what I can tell, the main issues are caused by us not being able to maintain global variables. Before, the icon solid setting was decided by an object called `wellknown`, and triggered by a message being passed. The icon being set to a circle with a green border was decided by a global boolean `sendSignal`.

**Comment by SebastianZimmeck** [comment] 2022-07-07 16:42
> I checked this out a little. From what I can tell, the main issues are caused by us not being able to maintain global variables.

That is a good observation. I could imagine that we will have this problem in other parts of our code as well. So, it would be a good to come up with a general approach (maybe, localStorage, Indexed DB, ...). We can also look at what other people are doing for their mv3 extensions. Are there blog posts, emerging best practices, ...?

**Comment by OliverWang13** [comment] 2022-07-07 17:23
I think I have been able to fix this, so I will open a pull request.

**Comment by OliverWang13** [comment] 2022-07-07 19:06
This has been resolved as well, so I will be closing it.

**Closed by OliverWang13** 2022-07-07 19:06 UTC
Labels: bug, mv3
